### ISSUE TITLE
插件已经卸载了，vscode也重启了，视频背景还在

### ISSUE THREAD

**Issue by Wangpengli0419** [dbfu/wukong-background-video#1]
插件已经卸载了，vscode也重启了，视频背景还在

**Comment by dbfu** [comment]
> 插件已经卸载了，vscode也重启了，视频背景还在

### 卸载方案

需要先在命令面板中搜索background-video.uninstall命令，命令执行成功后，再卸载插件，然后重启vscode，这个过程中不要关闭vscode或打开vscode。
卸载原理：执行卸载命令就是把写入的代码从vscode源码中删除，并且删除复制过去的视频，直接卸载插件，是不能删除代码和视频的，所以需要执行一个命令把代码和视频删除掉后，再卸载插件。
执行完删除命令后，还没卸载插件前，这时候不要打开或关闭vscode，因为每次重新打开vscode，插件都会把代码和视频复制过去，这时候再卸载插件就不行了，需要再执行一下卸载命令，紧接着卸载插件就行了。
有的人可能直接卸载插件，没有执行命令，这时候需要重新安装一下插件，然后执行上面步骤后，再卸载插件。
